# Generated by Django 3.1.1 on 2021-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_photo',
            field=models.ImageField(default='default.jpg', upload_to='featured_images'),
        ),
    ]
