# Generated by Django 3.1.1 on 2021-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event_featured_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=20)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('featured_photo', models.ImageField(default='default.jpg', upload_to='featured_images')),
                ('first_flight', models.CharField(max_length=4)),
            ],
        ),
    ]
