# Generated by Django 3.1.1 on 2021-01-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('featured_photo', models.ImageField(default='default.jpg', upload_to='featured_images')),
                ('base_plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plane')),
            ],
        ),
    ]
