# Generated by Django 3.1.1 on 2021-01-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_planevariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevariation',
            name='base_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='blog.plane'),
        ),
    ]
