# Generated by Django 3.1.1 on 2021-01-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_planevariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevariation',
            name='base_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='blog.plane'),
        ),
        migrations.AlterField(
            model_name='planevariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlaneImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='default.jpg', upload_to='featured_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.plane')),
            ],
        ),
    ]
