# Generated by Django 3.1.1 on 2021-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210114_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
