# Generated by Django 3.1.1 on 2021-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210114_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='id',
        ),
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
